public class CaseUtil_CCP{
    public static boolean AssignEntlmnboolean = false;
    public static boolean AssignEntlmnboolean_update = false;
    public static boolean EmailMsgboolean = false;
    public static boolean AddEntlContact = false;
    public static boolean updateCaseboolean= false;
    public static boolean Countoncaseboolean = false;
    public static boolean KeepEscationtrueboolean = false;
    public static boolean KeepEscationAfterUpdate = false;
    public static boolean updateCaseboolean1 = false;
    public static boolean UpdateCasewithEmailDatails = false;
    public static boolean KeepEscationBeforeInsert = false;
    public static boolean CalculateBusinessHoursAgesInsert = false;
    public static boolean CalculateBusinessHoursAgesUpdate = false;
    public static boolean BI_Email_BulkEmailCustomer = false;
    
    
}