.itb-table-style-01{width:100%;border-collapse:collapse;margin:0px;border:1px solid #ECECEC;}
.itb-table-style-01 th{font-size:14px;font-weight:normal;color:black;font-weight:bold;border-bottom:2px solid #6678b1;padding:10px 8px;border:1px solid #ECECEC;text-align:center;}
.itb-table-style-01 td{font-size:12px;border-bottom:1px solid #ccc;padding:10px 8px;border:1px solid #ECECEC;text-align:center;}
.itb-table-style-01 tbody tr:hover td{border:1px solid #ECECEC;}